services:
  - type: web
    name: art-on-the-wall
    runtime: node
    plan: free
    buildCommand: npm ci && npx prisma generate && npx prisma migrate deploy && npm run build && cp -r public .next/standalone/public
    startCommand: node .next/standalone/server.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: NODE_ENV
        value: production
